version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./front/public:/var/www/html/public"
      - "./back/public:/var/www/html/public/api"
    ports:
      - "8000:80"
    restart: always
    depends_on:
      - php
      - mysql
    command: ["nginx-debug", "-g", "daemon off;"]
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    restart: always
    volumes:
      - "./back/public:/var/www/html/public/api"
      - "./back/app:/var/www/html/app"
  composer:
    image: "composer"
    volumes:
      - "./back/app:/app"
    command: install
  mysql:
    image: mysql
    restart: always
    env_file:
      - ".env"
    volumes:
      - "./data/db/mysql:/var/lib/mysql"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
