version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./front/public:/var/www/html/public"
      - "./back/public:/var/www/html/public/api"
    ports:
      - "8000:80"
    restart: always
    command: ["nginx-debug", "-g", "daemon off;"]
